#include "modules/FeatureCatalog.h"

namespace cloud9 {

const std::vector<FeatureDescriptor>& featureCatalog() {
    static const std::vector<FeatureDescriptor> catalog = {
        // Combat
        {"Killaura", "Auto-attack entities within a configured range", ModuleCategory::Combat, SafetyClass::Moderate, false},
        {"Aimbot", "Adjust aim toward a selected target", ModuleCategory::Combat, SafetyClass::Moderate, false},
        {"Reach", "Change the requested attack distance", ModuleCategory::Combat, SafetyClass::Moderate, false},
        {"MobAura", "Target hostile mobs automatically", ModuleCategory::Combat, SafetyClass::Moderate, false},
        {"Hitbox", "Change target hitbox handling", ModuleCategory::Combat, SafetyClass::Moderate, false},
        {"AutoClicker", "Generate repeated mouse clicks", ModuleCategory::Combat, SafetyClass::Safe, false},
        {"AutoTotem", "Move a totem to the offhand when needed", ModuleCategory::Combat, SafetyClass::Safe, false},
        {"AutoGap", "Consume a golden apple at a health threshold", ModuleCategory::Combat, SafetyClass::Safe, false},
        {"AutoPot", "Use a configured potion when conditions match", ModuleCategory::Combat, SafetyClass::Moderate, false},
        {"Criticals", "Alter attack timing for critical hits", ModuleCategory::Combat, SafetyClass::Moderate, false},
        {"Velocity", "Change incoming knockback handling", ModuleCategory::Combat, SafetyClass::Moderate, false},
        {"AntiBot", "Filter duplicate or synthetic entities", ModuleCategory::Combat, SafetyClass::Safe, false},
        // Movement
        {"Freecam", "Detach a visual camera from the player", ModuleCategory::Movement, SafetyClass::Safe, false},
        {"NoFall", "Change fall-damage handling", ModuleCategory::Movement, SafetyClass::Moderate, false},
        {"InventoryMove", "Allow movement while a menu is open", ModuleCategory::Movement, SafetyClass::Safe, false},
        {"AutoSprint", "Request sprint while moving forward", ModuleCategory::Movement, SafetyClass::Safe, false},
        {"AutoSneak", "Request sneak near configured edges", ModuleCategory::Movement, SafetyClass::Safe, false},
        {"NoSlowdown", "Change item-use movement slowdown", ModuleCategory::Movement, SafetyClass::Moderate, false},
        {"Speed", "Change movement speed", ModuleCategory::Movement, SafetyClass::Detected, false},
        {"Fly", "Change gravity and flight handling", ModuleCategory::Movement, SafetyClass::Detected, false},
        {"Step", "Change the height of walkable ledges", ModuleCategory::Movement, SafetyClass::Moderate, false},
        {"FastLadder", "Change ladder and vine movement speed", ModuleCategory::Movement, SafetyClass::Moderate, false},
        {"Jesus", "Change water movement handling", ModuleCategory::Movement, SafetyClass::Detected, false},
        {"ElytraFly", "Change elytra flight physics", ModuleCategory::Movement, SafetyClass::Detected, false},
        {"LongJump", "Change jump distance", ModuleCategory::Movement, SafetyClass::Detected, false},
        {"Spider", "Change wall-climbing handling", ModuleCategory::Movement, SafetyClass::Detected, false},
        {"Scaffold", "Place blocks beneath a moving player", ModuleCategory::Movement, SafetyClass::Detected, false},
        {"Parkour", "Time jumps at parkour edges", ModuleCategory::Movement, SafetyClass::Safe, false},
        {"NoWeb", "Change cobweb movement slowdown", ModuleCategory::Movement, SafetyClass::Moderate, false},
        {"IceSpeed", "Change local ice friction", ModuleCategory::Movement, SafetyClass::Safe, false},
        // Player
        {"AutoArmor", "Choose armor from an inventory snapshot", ModuleCategory::Player, SafetyClass::Safe, false},
        {"AutoTool", "Choose an efficient tool for a block", ModuleCategory::Player, SafetyClass::Safe, false},
        {"AutoFish", "Detect a fishing-bobber event", ModuleCategory::Player, SafetyClass::Safe, false},
        {"ChestStealer", "Move items from a container snapshot", ModuleCategory::Player, SafetyClass::Safe, false},
        {"BlockReach", "Change requested block interaction distance", ModuleCategory::Player, SafetyClass::Moderate, false},
        {"InventorySort", "Sort a local inventory model", ModuleCategory::Player, SafetyClass::Safe, false},
        {"FastPlace", "Change local placement delay", ModuleCategory::Player, SafetyClass::Moderate, false},
        {"FastBreak", "Change local block break timing", ModuleCategory::Player, SafetyClass::Detected, false},
        {"Nuker", "Break many blocks automatically", ModuleCategory::Player, SafetyClass::Detected, false},
        {"Timer", "Change client tick pacing", ModuleCategory::Player, SafetyClass::Detected, false},
        {"AntiAFK", "Perform a periodic local activity", ModuleCategory::Player, SafetyClass::Safe, false},
        {"AutoRespawn", "Activate respawn when the screen is shown", ModuleCategory::Player, SafetyClass::Safe, false},
        {"AutoReconnect", "Schedule a reconnect after disconnect", ModuleCategory::Player, SafetyClass::Safe, false},
        {"MiddleClickFriend", "Toggle a player in the friend list", ModuleCategory::Player, SafetyClass::Safe, false},
        {"ChatFilter", "Filter local chat messages", ModuleCategory::Player, SafetyClass::Safe, false},
        {"NoRotate", "Change server rotation handling", ModuleCategory::Player, SafetyClass::Moderate, false},
        {"NoSwing", "Hide local arm swing animation", ModuleCategory::Player, SafetyClass::Safe, false},
        {"Offhand", "Swap a configured item to the offhand", ModuleCategory::Player, SafetyClass::Safe, false},
        {"AutoEat", "Consume food at a hunger threshold", ModuleCategory::Player, SafetyClass::Safe, false},
        {"AutoDrop", "Drop items matching a local filter", ModuleCategory::Player, SafetyClass::Safe, false},
        {"NoHurtCam", "Remove local hurt-camera motion", ModuleCategory::Player, SafetyClass::Safe, false},
        {"NoWeather", "Hide local weather particles", ModuleCategory::Player, SafetyClass::Safe, false},
        {"NoFog", "Hide local fog effects", ModuleCategory::Player, SafetyClass::Safe, false},
        {"UnlockAllRecipes", "Show all recipes in the local recipe book", ModuleCategory::Player, SafetyClass::Safe, false},
        {"CraftingSearch", "Filter recipes by text", ModuleCategory::Player, SafetyClass::Safe, false},
        {"QuickCraft", "Craft a maximum batch in a local model", ModuleCategory::Player, SafetyClass::Safe, false},
        // Visual
        {"Fullbright", "Expose a renderer brightness override", ModuleCategory::Visual, SafetyClass::Safe, true},
        {"Xray", "Filter opaque blocks in a renderer", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"ChunkBorders", "Render chunk boundary geometry", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"Tracers", "Render lines toward selected entities", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"PlayerESP", "Render player overlay geometry", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"MobESP", "Render mob overlay geometry", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"ItemESP", "Render dropped-item overlay geometry", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"StorageESP", "Render storage overlay geometry", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"Nametags", "Render enhanced entity labels", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"VoidESP", "Highlight void-facing cells", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"BreakProgress", "Render local block break progress", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"BlockOverlay", "Outline the selected block", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"Chams", "Render entities with a flat overlay", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"Breadcrumbs", "Render a trail from snapshot positions", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"Waypoints", "Render named world locations", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"TimeChanger", "Override local displayed time", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"WeatherChanger", "Override local displayed weather", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"Zoom", "Change local camera zoom", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"ViewModel", "Adjust local first-person model placement", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"CustomCrosshair", "Render a replacement crosshair", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"ItemPhysics", "Change dropped-item presentation", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"CustomPanorama", "Select a local menu panorama", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"CameraClip", "Change local third-person camera clipping", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"NoRender", "Disable selected local render elements", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"FreecamRender", "Render the player body during freecam", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"WorldBorder", "Render a local world border", ModuleCategory::Visual, SafetyClass::Safe, false},
        {"HealthBar", "Render snapshot health bars", ModuleCategory::Visual, SafetyClass::Safe, false},
        // HUD
        {"ArrayList", "List enabled modules", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"ArmorHUD", "Display armor snapshot data", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"PotionHUD", "Display active effects", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"TargetHUD", "Display selected target data", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"Coordinates", "Display player coordinates", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"FPS Counter", "Display frame rate", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"TPS Counter", "Display measured tick rate", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"Ping Display", "Display measured latency", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"MemoryUsage", "Display process memory statistics", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"Speedometer", "Display snapshot movement speed", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"Keystrokes", "Display local input state", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"CPS Counter", "Display local click rate", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"Clock", "Display wall-clock time", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"ReachDisplay", "Display a measured local distance", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"SessionInfo", "Display session statistics", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"Watermark", "Display Cloud9 branding", ModuleCategory::HUD, SafetyClass::Safe, false},
        {"NotificationSystem", "Display local notifications", ModuleCategory::HUD, SafetyClass::Safe, false},
        // Automation
        {"AutoWoodFarmer", "Plan a wood-farming route", ModuleCategory::Automation, SafetyClass::Moderate, false},
        {"AutoMiner", "Plan a strip-mining route", ModuleCategory::Automation, SafetyClass::Moderate, false},
        {"AutoBreeder", "Plan animal-feeding actions", ModuleCategory::Automation, SafetyClass::Moderate, false},
        {"AutoFarm", "Plan crop harvest and replant actions", ModuleCategory::Automation, SafetyClass::Moderate, false},
        {"TradeScanner", "Compare trade snapshots to a wishlist", ModuleCategory::Automation, SafetyClass::Safe, false},
        {"TradeReroller", "Plan villager job-site changes", ModuleCategory::Automation, SafetyClass::Moderate, false},
        {"VillagerBreeder", "Plan villager breeding actions", ModuleCategory::Automation, SafetyClass::Moderate, false},
        {"HallBuilder", "Plan block placement from a schematic", ModuleCategory::Automation, SafetyClass::Moderate, false},
        // Schematic
        {"SchematicLoader", "Load NBT-based schematic formats", ModuleCategory::Schematic, SafetyClass::Safe, false},
        {"SchematicRenderer", "Produce schematic overlay geometry", ModuleCategory::Schematic, SafetyClass::Safe, false},
        {"LayerSystem", "Filter schematic blocks by Y layer", ModuleCategory::Schematic, SafetyClass::Safe, false},
        {"SchematicPlacement", "Transform and anchor a schematic", ModuleCategory::Schematic, SafetyClass::Safe, false},
        {"ResourceList", "Account for schematic resources", ModuleCategory::Schematic, SafetyClass::Safe, false},
        {"SchematicVerifier", "Compare a schematic with a block reader", ModuleCategory::Schematic, SafetyClass::Safe, false},
        {"SchematicSearch", "Find block states in a schematic", ModuleCategory::Schematic, SafetyClass::Safe, false},
        {"SchematicUI", "Expose schematic controls to a host UI", ModuleCategory::Schematic, SafetyClass::Safe, false},
        // GUI
        {"ClickGUI", "Expose module controls to a host UI", ModuleCategory::GUI, SafetyClass::Safe, false},
        {"HUDEditor", "Edit host HUD element positions", ModuleCategory::GUI, SafetyClass::Safe, false},
        {"Console", "Expose the local log buffer", ModuleCategory::GUI, SafetyClass::Safe, false},
    };
    return catalog;
}

} // namespace cloud9
