#pragma once

#ifndef CLOUD9_VERSION_MAJOR
#define CLOUD9_VERSION_MAJOR 0
#endif
#ifndef CLOUD9_VERSION_MINOR
#define CLOUD9_VERSION_MINOR 1
#endif
#ifndef CLOUD9_VERSION_PATCH
#define CLOUD9_VERSION_PATCH 0
#endif

#define CLOUD9_VERSION_STRING_HELPER(major, minor, patch) #major "." #minor "." #patch
#define CLOUD9_VERSION_STRING_VALUE(major, minor, patch) CLOUD9_VERSION_STRING_HELPER(major, minor, patch)
#define CLOUD9_VERSION_STRING CLOUD9_VERSION_STRING_VALUE(CLOUD9_VERSION_MAJOR, CLOUD9_VERSION_MINOR, CLOUD9_VERSION_PATCH)
